### ISSUE TITLE
All is granted because nothing is managed

### ISSUE THREAD

**Issue by insideone** [fxpio/fxp-security-bundle#20]
I have a config without any fxp_security.permissions defined, because I store permissions in database. In this setup all checks are granted, because [PermissionManager::doIsManaged](https://github.com/fxpio/fxp-security/blob/master/Permission/PermissionManager.php#L113) returns false, because $this->hasConfig returns false, because it checks fxp_security.permissions which is empty in my case.

Why should I setup fxp_security.permissions when I already have all my configuration saved to database? Is it intentional behavior?

My current workaround:
```
  permissions:
    App\Entity\Event: ~
```

Anyway, thanks for the great bundle. Maybe I just don't figure out how it must be configured.

**Comment by francoispluchino** [comment]
Indeed, you must at least activate the permissions for each desired entity. In this way, checking can be optimized and avoids including unnecessary entities in the query to retrieve permissions in database.

**Comment by insideone** [comment]
I thought about such reason, but if application uses only fxp checks, then such optimization doesn't matter, does it? But in general... yes.

I'm little bit new to symfony dependency injection, but maybe there is a way to autowire supported app entities to permissions? I mean not in the current state, but is it possible and acceptable for you?

I think such implementation would be great

```yml
fxp_security:
   autowire_permissions: true
```

App\Entity\Event.php
```php
/**
 * @HasPermissions()
 */
class Event
```

If you agree I can try to do this on my own and make PR in future

**Comment by francoispluchino** [comment]
Precisely, I planned to work this week on the creation of annotation to configure the permissions, the identity types and the sharing subjects directly on the entities via the annotations. Initially, I was thinking of doing it this morning, but I have a job to do before, so I'll do it as soon as possible.

It will not be the `autowire_permissions` option, but it will be under the `annotations` option that already exists (must be confirmed, because I think I'll refactor annotations to no longer depend of the `sensio/framework-extra-bundle` dependency).

**Comment by francoispluchino** [comment]
The annotations to configure the global permissions and the sharing configuration have been added by:
- https://github.com/fxpio/fxp-security/compare/1beee8b3e75d1e0ecb3aa488bbcf5313da578b39...cf98e890484615e975d7586e5a5081738b98cbf7
- https://github.com/fxpio/fxp-security-bundle/compare/bcf696055f685a14b934949c9cce3b1b2e6a42bf...63d31e28913d057efc03fa176b0daf6b443bab1e

You can see the doc to use the [annotations](https://github.com/fxpio/fxp-security-bundle/blob/master/Resources/doc/annotations.md).

Regarding your initial question, and with the commit fxpio/fxp-security@1dccbdfd216d8bdee2cda45621b49a74018ca97a, the permission voter now returns the Abstain Access value if the subject is not managed. As a result, the authorization checker will return the `false` value if the entity class is not managed by the permission manager.
