### ISSUE TITLE
Role:_toString() declaration

### ISSUE THREAD

**Issue by zhenya91** [fxpio/fxp-security-bundle#23]
Hello!
I'm trying to update my Symfony project to 4.3.4 version.
So. I used FXP-security-bundle to organize RBAC functionality.
When I upgrade Symfony from version 4.2 to version 4.3.4, I get an error message:
```
 Declaration of Fxp\Component\Security\Model\Role::__toString() must be compatible with Symfony\Component\Security\Core\Role\Role::__toString(): string in /vendor/fxp/security/Model/Role.php on line 24
```
I found out that In Symfony Security Bundle of version 4.4 was added the declaration of `toString` function to the `Symfony\Component\Security\Core\Role\Role` class. 
And the difference is:
FXP:
```
 /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->getRole();
    }
```
and Symfony Security:
```
    public function __toString(): string
    {
        return $this->role;
    }
```
as you can see, there's no typehint(`:string`).
How can I resolve this problem?

**Comment by nikolaysmeh** [comment]
the same for me

**Comment by francoispluchino** [comment]
Do you use the 1.1 version or the 2.0@dev version? The 2.0 version is compatible with the Symfony 4.3.

**Comment by zhenya91** [comment]
Hi. 
Thank you for the answer.
I used to use version 1.1.
But then I changed the version to "dev" and it works great. Thank you.
I think it would be nice if you added the information about version 2.0 the main README.md file (At least some notice about compability with latest version of Symfony).
Thanks.

**Comment by francoispluchino** [comment]
Effectively, adding the information in the readme could help :-)
